package com.team.my_gorcery;

public class Constants {

    public static final String FCM_KEY = "AAAAZr2fnb0:APA91bHKiANFsdMzk0St0J6_irtEqw9GGS3hKohs9MZ0cLbXzaZJMXoBlQX9ZcgxtCrEPx6xSIzdI24jSa4ZFzCmPH41AxcemNe5ad38tCQ1o2WmkUMBOKMvmOJJSPoPGKfUl8i4TX5D";
    public static final String FCM_TOPIC = "PUSH_NOTIFICATIONS";

    //Product Categories
    public  static final String[] productcategory = {

            "Beverages",
            "Beauty and Personal Care",
            "Baby Kids",
            "Biscuits and Dairy",
            "Cooking Needs",
            "Frozen Food",
            "Fruits",
            "Pet",
            "Pharmacy",
            "Vegetables",
            "Farm Products",
            "Electronics",
            "Timepieces",
            "Watches",
            "Jewelry",
            "Eyewears",
            "Apparels for Men",
            "Apparels for Women",
            "Vehicles & Accessories",
            "Sports & Accessories",
            "Furniture",
            "Women Clothing",
            "Tools",
            "Underwear & Sleepwears",
            "Toys & Hobbies",
            "Shoes",
            "Security & Protection",
            "Novelty & Special Use",
            "Luggage & Bags",
            "lights & Lighting",
            "Home Improvement",
            "Home Appliances",
            "Home & Garden",
            "Hair & Extensions",
            "Education & Office Needs",
            "CellPhones & Telecommunication",
            "Automobiles & Motorcycles",
            "Mother & Kids",
            "Weddings & Events",
            "Laptop & Accessories",
            "Sports & Accessories",
            "Furniture",
            "Women Clothing",
            "Others"
    };

    public  static final String[] productcategory1 = {

             "All",
            "Beverages",
            "Beauty and Personal Care",
            "Baby Kids",
            "Biscuits and Dairy",
            "Cooking Needs",
            "Frozen Food",
            "Fruits",
            "Pet",
            "Pharmacy",
            "Vegetables",
            "Farm Products",
            "Electronics",
            "Timepieces",
            "Watches",
            "Jewelry",
            "Eyewears",
            "Apparels for Men",
            "Apparels for Women",
            "Vehicles & Accessories",
            "Sports & Accessories",
            "Furniture",
            "Women Clothing",
            "Tools",
            "Underwear & Sleepwears",
            "Toys & Hobbies",
            "Shoes",
            "Security & Protection",
            "Novelty & Special Use",
            "Luggage & Bags",
            "lights & Lighting",
            "Home Improvement",
            "Home Appliances",
            "Home & Garden",
            "Hair & Extensions",
            "Education & Office Needs",
            "CellPhones & Telecommunication",
            "Automobiles & Motorcycles",
            "Mother & Kids",
            "Weddings & Events",
            "Laptop & Accessories",
            "Sports & Accessories",
            "Furniture",
            "Women Clothing",
            "Others"
    };
}
